import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class NationaliteService {
  
  nationalites: any[] = [
    " Afghan " ,
    " Albanaise " ,
    " Algérienne" ,
    " Américain" ,
    " Andorran " ,
    " Angolaise " ,
    " Antiguaise " ,
    " Argentin " ,
    " Arménienne " ,
    " Australienne " ,
    " Autrichienne " ,
    " Azerbaïdjanaise " ,
    " Bahaméen " ,
    " Bahreïni " ,
    " Bangladaise " ,
    " barbadienne " ,
    " Barbudiennes " ,
    " Botswanaise " ,
    " biélorusse " ,
    " Belge " ,
    " Bélizienne " ,
    " béninois" ,
    " Bhoutanaise " ,
    " Boliviennene " ,
    " bosniaque " ,
    " Brésilienne " ,
    " Britannique" ,
    " Brunéienne " ,
    " Bulgare " ,
    " burkinabé" ,
    " Birman " ,
    " burundaise " ,
    " Cambodgienne " ,
    " camerounaise" ,
    " Canadienne" ,
    " capverdienne " ,
    " Centrafricain" ,
    " tchadienne " ,
    " Chilienne " ,
    " chinois" ,
    " colombienne" ,
    " comorienne " ,
    " congolaise" ,
    " costaricienne " ,
    " croate " ,
    " Cubain " ,
    " Chypriote " ,
    " Tchèque " ,
    " danois " ,
    " Djibouti " ,
    " Dominicain " ,
    " Néerlandaise " ,
    " Timoraise de l'Est" ,
    " équatorienne " ,
    " Égyptienne" ,
    " émirienne " ,
    " équato-guinéen" ,
    " érythréen" ,
    " Estonienne " ,
    " éthiopienne" ,
    " Fidji " ,
    " philippin " ,
    " Finnois " ,
    " française " ,
    " Gabonaise " ,
    " gambienne" ,
    " géorgienne " ,
    " Allemand " ,
    " Ghanéen " ,
    " grec" ,
    " Grenadienne " ,
    " Guatémaltèque " ,
    " Guinée-Bissau " ,
    " guinéen " ,
    " guyanaise " ,
    " Haïtienne " ,
    " herzégovinienne " ,
    " Hondurienne " ,
    " Hongrois " ,
    " I-Kiribati " ,
    " Islandaise " ,
    " Indienne " ,
    " Indonésienne " ,
    " Iranienne" ,
    " irakienne" ,
    " Irlandaise " ,
    " Israélienne" ,
    " italienne " ,
    " Ivoirienne " ,
    " jamaïcain " ,
    " japonaise " ,
    " Jordanienne " ,
    " Kazakhstanaise " ,
    " Kényan " ,
    " Kittienne et Névisienne " ,
    " Koweïtienne " ,
    " Kirghize " ,
    " Laotienne " ,
    " Letton " ,
    " Libanaise " ,
    " Libérienne " ,
    " Libyen " ,
    " Liechtensteinois " ,
    " Lituanienne " ,
    " Luxembourgeois " ,
    " Macédonienne " ,
    " Malgache" ,
    " Malawienne " ,
    " Malaiseienne " ,
    " Maldivienne " ,
    " Malienne" ,
    " maltaise " ,
    " Marshallaise " ,
    " mauritanienne" ,
    " mauricienne " ,
    " Mexicain " ,
    " Micronésienne " ,
    " Moldave " ,
    " monégasque " ,
    " mongole " ,
    " Marocain " ,
    " Mosotho " ,
    " Motswana " ,
    " Mozambicain " ,
    " namibienne " ,
    " Nauruan " ,
    " Népalaise " ,
    " néo-zélandaise" ,
    " nicaraguayen " ,
    " Nigérian " ,
    " Nigérienne " ,
    " nord-coréen" ,
    " Irlandaise du Nord " ,
    " Norvégienne " ,
    " Omanaise " ,
    " Pakistanaise " ,
    " Palaos " ,
    " panaméen " ,
    " papouan-néo-guinéen" ,
    " Paraguayen " ,
    " Péruvienne " ,
    " Polonaise " ,
    " Portugaise " ,
    " qatari " ,
    " Roumain " ,
    " Russe" ,
    " rwandaise" ,
    " Sainte Luciennene " ,
    " salvadorienne " ,
    " Samoan " ,
    " Saint-Marin " ,
    " Sao Toméen " ,
    " saoudienne " ,
    " Ecossaise " ,
    " sénégalaise" ,
    " serbe " ,
    " Seychellois " ,
    " sierra léonaise" ,
    " singapourienne " ,
    " slovaque " ,
    " slovène " ,
    " Salomonienne " ,
    " Somalienne " ,
    " Sud-africain" ,
    " sud-coréen " ,
    " Espagnol " ,
    " sri-lankaise" ,
    " soudanaise " ,
    " Surinam " ,
    " Swazi " ,
    " Suédois " ,
    " Suisse " ,
    " Syrienne " ,
    " Taïwanaise " ,
    " Tadjik " ,
    " tanzanienne " ,
    " Thaï " ,
    " togolaise" ,
    " Tongienne " ,
    " Trinidadienne ou Tobagonienne " ,
    " Tunisienne " ,
    " turc " ,
    " Tuvaluan " ,
    " Ougandaise " ,
    " Ukrainienne " ,
    " uruguayen " ,
    " Ouzbek " ,
    " Vénézuélienne " ,
    " Vietnamienne " ,
    " gallois " ,
    " Yéménite " ,
    " zambienne " ,
    " Zimbabwéen"
 ];

  constructor() {}
}
