import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class NationaliteService {
  
  nationalites: any[] = [
    " Afghan " ,
    " Albanaise " ,
    " Algérienne" ,
    " Américaine" ,
    " Andorran " ,
    " Angolaise " ,
    " Antiguaise " ,
    " Argentin " ,
    " Arménienne " ,
    " Australienne " ,
    " Autrichienne " ,
    " Azerbaïdjanaise " ,
    " Bahaméenne " ,
    " Bahreïni " ,
    " Bangladaise " ,
    " barbadienne " ,
    " Barbudiennes " ,
    " Botswanaise " ,
    " biélorusse " ,
    " Belge " ,
    " Bélizienne " ,
    " béninois" ,
    " Bhoutanaise " ,
    " Boliviennene " ,
    " bosniaque " ,
    " Brésilienne " ,
    " Britannique" ,
    " Brunéienne " ,
    " Bulgare " ,
    " burkinabé" ,
    " Birman " ,
    " burundaise " ,
    " Cambodgienne " ,
    " camerounaise" ,
    " Canadienne" ,
    " capverdienne " ,
    " Centrafricaine" ,
    " tchadienne " ,
    " Chilienne " ,
    " chinois" ,
    " colombienne" ,
    " comorienne " ,
    " congolaise" ,
    " costaricienne " ,
    " croate " ,
    " Cubaine " ,
    " Chypriote " ,
    " Tchèque " ,
    " danois " ,
    " Djibouti " ,
    " Dominicaine " ,
    " Néerlandaise " ,
    " Timoraise de l'Est" ,
    " équatorienne " ,
    " Égyptienne" ,
    " émirienne " ,
    " équato-guinéenne" ,
    " érythréenne" ,
    " Estonienne " ,
    " éthiopienne" ,
    " Fidji " ,
    " philippin " ,
    " Finnois " ,
    " française " ,
    " Gabonaise " ,
    " gambienne" ,
    " géorgienne " ,
    " Allemand " ,
    " Ghanéenne " ,
    " grec" ,
    " Grenadienne " ,
    " Guatémaltèque " ,
    " Guinée-Bissau " ,
    " guinéenne " ,
    " guyanaise " ,
    " Haïtienne " ,
    " herzégovinienne " ,
    " Hondurienne " ,
    " Hongrois " ,
    " I-Kiribati " ,
    " Islandaise " ,
    " Indienne " ,
    " Indonésienne " ,
    " Iranienne" ,
    " irakienne" ,
    " Irlandaise " ,
    " Israélienne" ,
    " italienne " ,
    " Ivoirienne " ,
    " jamaïcaine " ,
    " japonaise " ,
    " Jordanienne " ,
    " Kazakhstanaise " ,
    " Kényan " ,
    " Kittienne et Névisienne " ,
    " Koweïtienne " ,
    " Kirghize " ,
    " Laotienne " ,
    " Letton " ,
    " Libanaise " ,
    " Libérienne " ,
    " Libyen " ,
    " Liechtensteinois " ,
    " Lituanienne " ,
    " Luxembourgeois " ,
    " Macédonienne " ,
    " Malgache" ,
    " Malawienne " ,
    " Malaiseienne " ,
    " Maldivienne " ,
    " Malienne" ,
    " maltaise " ,
    " Marshallaise " ,
    " mauritanienne" ,
    " mauricienne " ,
    " Mexicaine " ,
    " Micronésienne " ,
    " Moldave " ,
    " monégasque " ,
    " mongole " ,
    " Marocaine " ,
    " Mosotho " ,
    " Motswana " ,
    " Mozambicaine " ,
    " namibienne " ,
    " Nauruan " ,
    " Népalaise " ,
    " néo-zélandaise" ,
    " nicaraguayen " ,
    " Nigérian " ,
    " Nigérienne " ,
    " nord-coréenne" ,
    " Irlandaise du Nord " ,
    " Norvégienne " ,
    " Omanaise " ,
    " Pakistanaise " ,
    " Palaos " ,
    " panaméenne " ,
    " papouan-néo-guinéenne" ,
    " Paraguayen " ,
    " Péruvienne " ,
    " Polonaise " ,
    " Portugaise " ,
    " qatari " ,
    " Roumaine " ,
    " Russe" ,
    " rwandaise" ,
    " Sainete Luciennene " ,
    " salvadorienne " ,
    " Samoan " ,
    " Sainet-Marin " ,
    " Sao Toméenne " ,
    " saoudienne " ,
    " Ecossaise " ,
    " sénégalaise" ,
    " serbe " ,
    " Seychellois " ,
    " sierra léonaise" ,
    " singapourienne " ,
    " slovaque " ,
    " slovène " ,
    " Salomonienne " ,
    " Somalienne " ,
    " Sud-africaine" ,
    " sud-coréenne " ,
    " Espagnol " ,
    " sri-lankaise" ,
    " soudanaise " ,
    " Surinam " ,
    " Swazi " ,
    " Suédois " ,
    " Suisse " ,
    " Syrienne " ,
    " Taïwanaise " ,
    " Tadjik " ,
    " tanzanienne " ,
    " Thaï " ,
    " togolaise" ,
    " Tongienne " ,
    " Trinidadienne ou Tobagonienne " ,
    " Tunisienne " ,
    " turc " ,
    " Tuvaluan " ,
    " Ougandaise " ,
    " Ukraineienne " ,
    " uruguayen " ,
    " Ouzbek " ,
    " Vénézuélienne " ,
    " Vietnamienne " ,
    " gallois " ,
    " Yéménite " ,
    " zambienne " ,
    " Zimbabwéenne"
 ];

  constructor() {}
}
